server.port=8089

spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.chat.options.model=${OPTION_MODEL:gpt-5.4-nano}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL:gemini-2.5-flash-lite}


spring.ai.ollama.base-url=http://localhost:12434
spring.ai.ollama.chat.options.model=llama3.2:latest